### PR TITLE
Add installation notes for Ubuntu 16.04

### PR DESCRIPTION
**Pull request by Russell-Jones-OxPhys**
I guess a link to existing install docs would be helpful if they exist.

### CODE REVIEW

**Comment by encukou** [comment]
These instructions will become obsolete once the project is on PyPI (https://github.com/fedora-python/python-ethtool/issues/4).

Also, if you see a bug, please please file an issue for it instead of documenting that something doesn't work. It's better to fix the code.

**Comment by stratakis** [comment]
Following up @encukou 's comment, once 0.13 version is released, debian/ubuntu should update the package (not sure of the package update policy there), so `sudo apt-install  python-ethtool` should work fine. After that happens, we can include official installation instructions for different distributions.

Closing this PR. The issue can be revisited after the release of 0.13.

**Comment by hroncok** [comment]
Note: Some installation instructions might be handy in the README. For example the packages to install beforehand on Fedora and Debian/Ubuntu.

**Comment by Russell-Jones-OxPhys** [comment]
@stratakis 
And `sudo apt-install python3-ethtool` hopefully. Though that doesn't help people on Ubuntu LTS or older versions of Debian.

**Pull request closed without merging**
