### PR TITLE
This is not the package you are looking for

### PR DESCRIPTION
**Pull request by hroncok**

### CODE REVIEW

**Comment by stratakis** [comment]
Shouldn't we propose a definite alternative though?

**Comment by frenzymadness** [comment]
@stratakis What do you mean by "definite alternative"? The alternative is add in this PR.

**Comment by hroncok** [comment]
I'm unsure if can do everything ethtool can.

**Comment by stratakis** [comment]
@frenzymadness Apologies, I didn't quite speak my mind here. My issue is basically with the phrasing. Instead of a question in the end, it could be a more definitive phrasing. Something like:

> Try `netifaces <https://pypi.org/project/netifaces/>`_ instead.

**Pull request merged**
