### PR TITLE
New release 0.15

### PR DESCRIPTION
**Pull request by frenzymadness**
There are some unreleased bug fixes I need for downstream so doing a new release now.

### CODE REVIEW

**Comment by frenzymadness** [comment]
I have no idea why the CI has not started yet. Travis-ci.com project page is completely empty.

**Comment by frenzymadness** [comment]
There is no request for a build: https://www.travis-ci.com/github/fedora-python/python-ethtool/requests

**Comment by frenzymadness** [comment]
And when I try to trigger it manually, I get " Oh no! Oops, something went wrong, please try again.".

**Comment by frenzymadness** [comment]
I had to enable some beta program for fedora-python organization and then migrate the repository from travis-ci.org to travis-ci.com :disappointed:

**Comment by hroncok** [comment]
Consider also extending https://github.com/fedora-python/python-ethtool/blob/b8b09b69ef6d4f8a6f12a6c441305790060dd829/setup.py#L128

**Comment by frenzymadness** [comment]
> Consider also extending
> 
> https://github.com/fedora-python/python-ethtool/blob/b8b09b69ef6d4f8a6f12a6c441305790060dd829/setup.py#L128

Thank you. Fixed.

**Review by hroncok — APPROVED** [review]

**Pull request merged**
