### PR TITLE
Offload: adding set_gso(), get_gro() and set_gro() functions

### PR DESCRIPTION
**Pull request by RemyDelion**
https://github.com/fedora-python/python-ethtool/issues/37

### CODE REVIEW

**Comment by frenzymadness** [comment]
Thank you very much for your PR. It looks good to me but it needs one more review.

@stratakis could you please take a look?

**Comment by stratakis** [comment]
I am not so familiar with python-ethtool's codebase to do a review of such a new feature. @hroncok would you be able to chip in?

Also I see that some executable bits were removed in this PR (permissions changing from 755 to 644) on some files. Is this intentional?

**Comment by RemyDelion** [comment]
Concerning the permissions, no, it wasn't intentional. I didn't want to change any permission.

**Comment by hroncok** [comment]
> @hroncok would you be able to chip in?

Not really, sorry.

**Comment by frenzymadness** [comment]
Okay, our last chance, @encukou?

**Comment by RemyDelion** [comment]
I just fixup the file permissions (to 755).

**Comment by lootr** [comment]
That sounds great to me :)

**Comment by frenzymadness** [comment]
Okay, I don't see any reason why not merge this PR.

Thank you for your contribution!

**Comment by RemyDelion** [comment]
Thanks!

**Pull request merged**
