### PR TITLE
Release version 0.13, add CHANGES.rst entry

### PR DESCRIPTION
**Pull request by hroncok**
Releated https://github.com/fedora-python/python-ethtool/issues/4

### CODE REVIEW

**Comment by Sanqui** [comment]
A more interesting point is whether we want to release 0.13 or 1.0.  Following [Semantic Versioning](http://semver.org/), this sounds like a good time to release the first "major" stable version.

**Comment by hroncok** [comment]
We have no idea how "stable" this is. First we release this as 0.13. Will mention the PyPI thing first.

**Comment by hroncok** [comment]
Amended.

**Comment by Sanqui** [comment]
Since it's been used in production for several years, that calls for the API being called stable no matter possible bugs.  But let's go with 0.13 for now.

**Comment by hroncok** [comment]
Thanks for review. I'll merge it once releasing.

**Comment by hroncok** [comment]
We can have the discussion about 1.0 in a separate issue (feel free to open one), I just don't want to block the release any further.

**Pull request merged**
